options:
  source:
    type: string
    default: distro
    description: |
      Repository from which to install. May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Ubuntu Cloud Archive e.g.
      .
      cloud:<series>-<openstack-release>
      cloud:<series>-<openstack-release>/updates
      cloud:<series>-<openstack-release>/staging
      cloud:<series>-<openstack-release>/proposed
      .
      See https://wiki.ubuntu.com/OpenStack/CloudArchive for info on which
      cloud archives are available and supported.
  base-port:
    type: int
    default: 3306
    description: |
        Base port number for RW interface. RO, xRW and xRO will
        increment from base_port.
  ttl:
    type: float
    default: .5
    description: |
        Time to live (in seconds) of information in the metadata cache.
        Accepts either an integer or a floating point value. The granularity is
        limited to milliseconds, where 0.001 equates to one millisecond.
        Precision is truncated to the supported range; for example ttl=0.0119
        is treated as 11 milliseconds. The value 0 means that the metadata
        cache module queries the metadata continuously in a tight loop.
  auth_cache_refresh_interval:
    type: int
    default: 2
    description: |
        Time (in seconds) between the auth-cache refresh attempts. Defaults to
        2. The value must be smaller than auth_cache_ttl and ttl else Router
        won't start.
  auth_cache_ttl:
    type: int
    default: -1
    description: |
        Time (in seconds) until the cache becomes invalid if not refreshed.
        Defaults to -1 (infinite). The value must be larger than
        auth_cache_refresh_interval else Router won't start.
  max_connections:
    type: int
    default: 1024
    description: |
        If mysql router version < 8.0.27, this option will be set as max_connections
        in the config. Else will be max_total_connections.
        The max_connections is maximum number of connections to allow in direction to each MySQL
        routing sessions, with one for the RW unit and another one for the RO
        units of the MySQL innodb cluster. A valid range is between 1 and 65535.
        The max_total_connections is the maximum number of client connections handled by Router, to help
        prevent running out of the file descriptors. A valid
        range is between 1 and 9223372036854775807.
